# Generated by Django 5.1.7 on 2025-04-01 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket_mb2cpu', models.TextField(blank=True, verbose_name='Разъем материнка - процессор')),
                ('socket_mb2gpu', models.TextField(blank=True, verbose_name='Разъем материнка - видеокарта')),
                ('socket_mb2ssd', models.TextField(blank=True, verbose_name='Разъем материнка - ссд')),
                ('socket_mb2ram', models.TextField(blank=True, verbose_name='Разъем материнка - оперативка')),
                ('socket_mb2psu', models.TextField(blank=True, verbose_name='Разъем материнка - блок питания')),
                ('chipset', models.TextField(blank=True, verbose_name='Чипсет')),
                ('usb_ports', models.IntegerField(null=True, verbose_name='ЮСБ разъемы')),
                ('frequency', models.IntegerField(null=True, verbose_name='Частота')),
                ('recommended_power_supply', models.IntegerField(null=True, verbose_name='Рекомендованая мощность питания')),
                ('psu_power', models.IntegerField(null=True, verbose_name='Мощность блока питания')),
                ('memory_size', models.IntegerField(null=True, verbose_name='Объем памяти')),
                ('model_series', models.TextField(blank=True, verbose_name='Серия модели')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='main.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Комплектующие',
                'verbose_name_plural': 'Комплектующие',
                'ordering': ['product'],
            },
        ),
    ]
