# Generated by Django 5.1.7 on 2025-04-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='chipset',
            field=models.TextField(blank=True, null=True, verbose_name='Чипсет'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='frequency',
            field=models.IntegerField(blank=True, null=True, verbose_name='Частота'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='memory_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объем памяти'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='model_series',
            field=models.TextField(blank=True, null=True, verbose_name='Серия модели'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='psu_power',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мощность блока питания'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='recommended_power_supply',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рекомендованая мощность питания'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='socket_mb2cpu',
            field=models.TextField(blank=True, null=True, verbose_name='Разъем материнка - процессор'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='socket_mb2gpu',
            field=models.TextField(blank=True, null=True, verbose_name='Разъем материнка - видеокарта'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='socket_mb2psu',
            field=models.TextField(blank=True, null=True, verbose_name='Разъем материнка - блок питания'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='socket_mb2ram',
            field=models.TextField(blank=True, null=True, verbose_name='Разъем материнка - оперативка'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='socket_mb2ssd',
            field=models.TextField(blank=True, null=True, verbose_name='Разъем материнка - ссд'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='usb_ports',
            field=models.IntegerField(blank=True, null=True, verbose_name='ЮСБ разъемы'),
        ),
    ]
