# Generated by Django 5.1.7 on 2025-04-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_productimage_thumbnail_productimage_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brief_technical_specifications',
            field=models.TextField(blank=True, null=True, verbose_name='Короткие технические характеристики'),
        ),
        migrations.AlterField(
            model_name='products',
            name='buttons',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество кнопок'),
        ),
        migrations.AlterField(
            model_name='products',
            name='display_diagonal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Диагональ дисплея'),
        ),
        migrations.AlterField(
            model_name='products',
            name='extra',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='products',
            name='guarantee',
            field=models.IntegerField(blank=True, null=True, verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Габариты'),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес'),
        ),
    ]
