# Generated by Django 5.1.7 on 2025-04-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_commenttoproduct_user_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commenttoproduct',
            old_name='post',
            new_name='product',
        ),
    ]
