# Generated by Django 5.1.7 on 2025-04-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_work', 'In Work'), ('closed', 'Closed')], default='new', max_length=10),
        ),
    ]
