# Generated by Django 5.1.7 on 2025-04-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_posts_is_published_posts_likes_posts_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
